DROP DATABASE IF EXISTS burger_db;
CREATE DATABASE burgers_db;
USE burger_db;

CREATE TABLE burgers (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
burger_name VARCHAR(100),
devoured BOOLEAN DEFAULT false
);

